---
resources:

- name: source-code
  type: git
  source:
    uri: git@code.clubber.me:sellbycell/paynet-transfer-merchant-proxy.git
    private_key: {{releasebot-private-key}}

jobs:

- name: job-build

  plan:

  - get: source-code
    trigger: true

  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.5-jdk-8-alpine
      inputs:
      - name: source-code
      run:
        path: "bash"
        args: ["source-code/concourse/test.sh"]
